### ISSUE TITLE
bug: Missing UTF-8 encoding for Navbar on "publications" page

### ISSUE THREAD

**Issue by joakimkistowski** [vikin91/BibSpace#27]
The encoding on the "publications" page seems to be wrong. It can not correctly display non-ANSI names in the navbar.

How to reproduce:
- Have a non-ANSI name
- Log in
- Click Publications -> Show papers
- Observe wrong characters in name in the top left

**Comment by vikin91** [comment]
Thanks for reporting! I may find some time at the end of the week to give a look. Just ping me occasionally in case that not happens :)
