### ISSUE TITLE
sometimes bib and abstract link also not working

### ISSUE THREAD

**Issue by dipenpatel235** [vikin91/BibSpace#29]
sometimes bib and abstract link also not working
i have try to fix from regenerate but not fixed all.

can u Help me how can fix it ?

Thanks

**Comment by vikin91** [comment]
Thanks for reporting this! 
I would need more information to be able to dig into your problem.
Are you using unique BibTeX keys for all your entries? This is important for this feature to work.
System should notify you if there are duplicates existing, but this check is easy to skip.

**Comment by dipenpatel235** [comment]
unique BibTeX keys for all your entries? - Yes

**Comment by dipenpatel235** [comment]
See in this screenshot first two bib is view when clicked on bib then it is not open on 3rd yellow highlighted.

let me know if you want any more info.

![not_open_yellow_highlited_link](https://user-images.githubusercontent.com/8135097/42165862-ece8367e-7e26-11e8-8234-e5d5b9593c10.PNG)

**Comment by vikin91** [comment]
Thanks for this screenshot. 
The translation of BibTeX code to HTML is the most challenging part, but I cannot see why this is not working currently. Could you paste here the Bibtex code of the third entry? 

The second entry uses non-standard type `@online` which is not officially supported by BibTeX and that is the reason why you do not see any text generated. You may need to change it to `@misc` and add a note that it is published online, for example: `note = {Published online}`.

**Comment by dipenpatel235** [comment]
here github in .bib extention not allowed so
i have attached file on dropbox link please download from there and check it.
https://www.dropbox.com/s/pj39o31xhalqhnj/citation.bib

Please look it and let me know

Thanks
Dipen Dalsaniya

**Comment by vikin91** [comment]
BibSpace processes single entries, so there is no need to upload entire bib files. 
I guess the third item is the following entry:

```bibtex
@article{doi:10.1177/1745691617693393,
author = {Tal Yarkoni and Jacob Westfall},
title ={Choosing Prediction Over Explanation in Psychology: Lessons From Machine Learning},
journal = {Perspectives on Psychological Science},
volume = {12},
number = {6},
pages = {1100-1122},
year = {2017},
doi = {10.1177/1745691617693393},
    note ={PMID: 28841086},

URL = {
        https://doi.org/10.1177/1745691617693393

},
eprint = {
        https://doi.org/10.1177/1745691617693393

}
,
    abstract = { Psychology has historically been concerned, first and foremost, with explaining the causal mechanisms that give rise to behavior. Randomized, tightly controlled experiments are enshrined as the gold standard of psychological research, and there are endless investigations of the various mediating and moderating variables that govern various behaviors. We argue that psychology’s near-total focus on explaining the causes of behavior has led much of the field to be populated by research programs that provide intricate theories of psychological mechanism but that have little (or unknown) ability to predict future behaviors with any appreciable accuracy. We propose that principles and techniques from the field of machine learning can help psychology become a more predictive science. We review some of the fundamental concepts and tools of machine learning and point out examples where these concepts have been used to conduct interesting and important psychological research that focuses on predictive research questions. We suggest that an increased focus on prediction, rather than explanation, can ultimately lead us to greater understanding of behavior. }
}
```

The entry looks okay and should be rendered properly. However to investigate more, you may want to try the following things:
- give it a different bibtex-key `@article{doi:10.1177/1745691617693393,` change to `@article{doi-10.1177-1745691617693393,` or any other more compact key
- make sure that commas follow the curly brackets, so change:
  ```
  }
  ,
  ``` 
  into: 
  ```
  },
  ```
and regenerate HTML for that entry.

As I said, HTML generation (including bib and abstract) are kind of tricky to implement. The generation uses build-it BibTeX binary from your system and each version has its own quirks.

Unfortunately, I do not have currently access to my test system, so I cannot try it locally. Let me pleas know if it helps or shall I look into it further later.

**Comment by dipenpatel235** [comment]
Actually i am using JabRef and that file is working fine with JabRef
But in JabRef issue is software based not web based.
and i am looking for some good one web based.

so if you  get time and try to make unique common platform to fix that type of minor-minor issue so it will good.
Because when user will upload that time each user is not technical person to what syntax need to change and bla bla bla.

Thanks
Dipen Dalsaniya

**Comment by vikin91** [comment]
Yes, I know this requirement is both: blessing, and hell.

BibSpace supports strictly only classical BibTeX formatting - this sets some limits, but on the other hand, you can be 100% sure, that a citation entry pasted into a paper by someone else will always look great and there will be no issues with presenting and citing your work.

There are many tools that support multiple extra fields and formats of citation entries. This usually results in creating a custom format that does not follow the original BibTeX rules. Unfortunately, each author that wants to cite your work will need to adapt such entry on their own. They may instead choose a different literature position and not cite your work as a result.

BibSpace moves the responsibility to keep entries clean to the author and I think that this is a valid design decision. Unfortunately, this forces you to do some work; if you have large literature base (papers that you author) then the polishing of the entries may be worth a try.

**Comment by dipenpatel235** [comment]
Thanks @vikin91  for valuable support and help
