### ISSUE TITLE
bug: Password reset not working

### ISSUE THREAD

**Issue by NSchmittUniWue** [vikin91/BibSpace#40]
Hello,
the password resets are not working properly (version 0.5.2). After a password reset, the user object variable `pass` has the new plaintext password, yet `check_password` in Function/Core.pm assumes an encrypted and salted password in `pass`. 
As far as I can see, this is due to line 324 in Controller/Login.pm setting the variable to the plaintext password instead of the encrypted and salted password generated in line 323.

**Comment by vikin91** [comment]
Thanks for reporting. I will give it a look in the next days.

**Comment by vikin91** [comment]
This issue should be now fixed for versions `>= 0.5.2 in branch`. 

Versions`0.5.2` and `0.5.3` have now their own branches to enable backporting bugfixes.

I would recommend you to do the migration to `0.5.3` and later to `0.6.0` when it is released – I solved a lot of internal problems in `0.6.0`. I am happy to support you in this migration in case you need help.
